"""Updated Albums

Revision ID: 291332f5b642
Revises: 9db8b8cac675
Create Date: 2026-01-13 19:09:47.330794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '291332f5b642'
down_revision: Union[str, Sequence[str], None] = '9db8b8cac675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('album_images_ids', postgresql.ARRAY(sa.Integer()), server_default=sa.text("'{}'::integer[]"), nullable=True))
    op.add_column('albums', sa.Column('album_videos_ids', postgresql.ARRAY(sa.Integer()), server_default=sa.text("'{}'::integer[]"), nullable=True))
    op.add_column('albums', sa.Column('album_raw_images_ids', postgresql.ARRAY(sa.Integer()), server_default=sa.text("'{}'::integer[]"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'album_raw_images_ids')
    op.drop_column('albums', 'album_videos_ids')
    op.drop_column('albums', 'album_images_ids')
    # ### end Alembic commands ###
