"""Added Albums

Revision ID: 9db8b8cac675
Revises: 98b4786d0c67
Create Date: 2026-01-13 19:02:56.652663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9db8b8cac675'
down_revision: Union[str, Sequence[str], None] = '98b4786d0c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('album_size', sa.BigInteger(), nullable=True))
    op.add_column('albums', sa.Column('album_cover_type', sa.String(), nullable=True))
    op.add_column('albums', sa.Column('album_cover_id', sa.Integer(), nullable=True))
    op.add_column('albums', sa.Column('album_images_count', sa.Integer(), nullable=True))
    op.add_column('albums', sa.Column('album_videos_count', sa.Integer(), nullable=True))
    op.add_column('albums', sa.Column('album_raw_images_count', sa.Integer(), nullable=True))
    op.add_column('albums', sa.Column('album_total_count', sa.Integer(), nullable=True))
    op.add_column('albums', sa.Column('album_location', sa.String(), nullable=True))
    op.add_column('albums', sa.Column('album_latitude', sa.Float(), nullable=True))
    op.add_column('albums', sa.Column('album_longitude', sa.Float(), nullable=True))
    op.add_column('albums', sa.Column('album_city', sa.String(), nullable=True))
    op.add_column('albums', sa.Column('album_state', sa.String(), nullable=True))
    op.add_column('albums', sa.Column('album_country', sa.String(), nullable=True))
    op.add_column('albums', sa.Column('album_description', sa.String(), nullable=True))
    op.add_column('albums', sa.Column('album_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('albums', sa.Column('album_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('albums', 'updated_at')
    op.drop_column('albums', 'created_at')
    op.add_column('images', sa.Column('album_ids', postgresql.ARRAY(sa.Integer()), server_default=sa.text("'{}'::integer[]"), nullable=True))
    op.add_column('raw_images', sa.Column('album_ids', postgresql.ARRAY(sa.Integer()), server_default=sa.text("'{}'::integer[]"), nullable=True))
    op.add_column('videos', sa.Column('album_ids', postgresql.ARRAY(sa.Integer()), server_default=sa.text("'{}'::integer[]"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'album_ids')
    op.drop_column('raw_images', 'album_ids')
    op.drop_column('images', 'album_ids')
    op.add_column('albums', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('albums', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('albums', 'album_updated_at')
    op.drop_column('albums', 'album_created_at')
    op.drop_column('albums', 'album_description')
    op.drop_column('albums', 'album_country')
    op.drop_column('albums', 'album_state')
    op.drop_column('albums', 'album_city')
    op.drop_column('albums', 'album_longitude')
    op.drop_column('albums', 'album_latitude')
    op.drop_column('albums', 'album_location')
    op.drop_column('albums', 'album_total_count')
    op.drop_column('albums', 'album_raw_images_count')
    op.drop_column('albums', 'album_videos_count')
    op.drop_column('albums', 'album_images_count')
    op.drop_column('albums', 'album_cover_id')
    op.drop_column('albums', 'album_cover_type')
    op.drop_column('albums', 'album_size')
    # ### end Alembic commands ###
