"""Add favourite column

Revision ID: aca6a66a3b5b
Revises: 
Create Date: 2026-01-12 22:22:19.225948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aca6a66a3b5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    op.add_column('raw_images', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    op.add_column('videos', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'is_favorite')
    op.drop_column('raw_images', 'is_favorite')
    op.drop_column('images', 'is_favorite')
    # ### end Alembic commands ###
