"""Updated Albums

Revision ID: cef2dd5b9edd
Revises: e7f20bf0c5dc
Create Date: 2026-01-17 13:27:37.925451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cef2dd5b9edd'
down_revision: Union[str, Sequence[str], None] = 'e7f20bf0c5dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_albums_album_name'), table_name='albums')
    op.create_index(op.f('ix_albums_album_name'), 'albums', ['album_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_albums_album_name'), table_name='albums')
    op.create_index(op.f('ix_albums_album_name'), 'albums', ['album_name'], unique=True)
    # ### end Alembic commands ###
